name: DEMO File

on:
  push:
    branches:
      - main

jobs:
  auto-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # ✅ Fix: removed extra slash

      - name: Give permission
        run: chmod +x demo.sh

      - name: Demo running
        run: ./demo.sh
